spring.application.name=regua-barbier
spring.datasource.url=${DB_URL}
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=true
api.security.token.secret=${JWT_SECRET}
mercado_pago_access_token=${MERCADO_PAGO_TOKEN}