spring:
  application:
    name: regua-barbier

  # Configuração da Conexão com o Banco
  datasource:
    url: jdbc:mysql://localhost:3306/regua_barbier_db?createDatabaseIfNotExist=true
    username: root
#    password: sua_senha_aqui
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuração do Hibernate/JPA
  jpa:
    hibernate:
      ddl-auto: validate # Importante: validate garante que o Flyway manda no banco
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Deixa as queries no console legíveis

  # Configuração do Flyway (Migrações)
  flyway:
    enabled: true
    locations: classpath:db/migration

# Configuração do Servidor
server:
  port: 8080
  error:
    include-message: always # Ajuda a debugar erros da API