spring.application.name=regua-barbier
spring.datasource.url=jdbc:mysql://localhost:3306/regua_barbier?createDatabaseIfNotExist=TRUE
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=true
springdoc.swagger-ui.path=/regua-barbier.html
springdoc.api-docs.path=/v1/api-docs